:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= OMCA (Oakland Museum of California) CollectionSpace migration

[IMPORTANT]
.*GitHub repository visibility*
====
Unlike most of our migration repositories, this one is publicly viewable. This is because:

* This migration code is almost entirely based on the patterns of data structures in CollectionSpace, which is open source
* Because it is based on known CollectionSpace data structures, little-to-no actual information about the client data is in the code
* Needing folks outside this GitHub organization to be able to see documentation in this repository, at least while the project is ongoing
====

toc::[]

== Migration stages

=== Extract

Pull the tables from the database, in CSV format.

* [x] Soft-deleted record data still in the database is omitted
* [x] Ensures the necessary id values for linkage outside the database are present

[NOTE]
====
Initially I planned to apply https://github.com/lyrasis/collectionspace-sql/blob/main/common_patterns.adoc#converting-date-values-to-site-timezone[the timezone shift required to export accurate date/times from hosted instances].

However, I determined that the database timezone was set to Pacific, not UTC. I confirmed on 2026-04-30 that stored date values in db, as-is, match expected data values in UI/XML.
====

The following commands (and associated https://github.com/dts-hosting/migration-cspace-omca/blob/main/lib/omca/db/queries.rb[queries]) are used extract the data from the database:

----
thor db:addtl_fields
thor db:blobs
thor db:contacts
thor db:extension_field_group
thor db:main
thor db:repeatable_field
thor db:repeatable_field_group
thor db:repeatable_in_group
thor db:structured_dates
thor db:subgroup_tables
----

`thor db:missing_id` is then run to verify all query output includes the expected id values

`thor db:tables_and_columns` can be used to pull a list of all fields in all tables.
I used this to match rows in Jessi's mappings spreadsheet table to the database table in which the data is stored.

The main record types in the source data are:

* collectionobject
* acquisition
* claim
* conditioncheck
* conservation
* exhibition
* group
* loanin
* loanout
* intake
* media
* movement
* objectexit
* restrictedmedia
* valuationcontrol
* citation
* concept
* location
* organization
* person
* place
* taxon

The main_tables extraction for these record types pulls the core, single-valued field data for each record type.

There are 154 other tables containing data that belongs to these record types.
These tables are categorized by the pattern of how the data in them gets merged into the main record types:

addtl_fields:: One row per main table row; Adds single-valued, standalone fields to core; All are custom to OMCA, and will need remapping according to specifications prepared by Jessi/Jadeen/OMCA.
extension_field_group:: The same as `repeatable_field_group`, except the field group is defined and used in multiple main record types.
repeatable_field:: One or more rows per main table row; Data from standalone multi-valued fields, such as a list of inventory statuses. Position of each value is indicated. Null `item` values removed.
repeatable_field_group:: One or more rows per main table; Data from repeatable groupings of fields, or "field blocks"; Position of each block is indicated.
repeatable_in_group:: One or more rows per group table row; Data from repeatable single field _inside a repeatable field block_; Positionality in play
subgroup_tables:: One or more rows per group_table row; Data from repeatable a repeatable field block inside another repeatable field block; Position of each block is indicated.
subrecord:: Blob and contact tables
structured_dates:: Combined data from `dategroup` and `structureddategroup` tables, in two files based on whether the date is top-level in record, or nested inside a field group; Both of these extracted tables have multiple target record types and different target date fields within those.

Other extract tasks:

* Vocabularies (Term Lists)
** [x] Extract all vocabulary terms used (`thor vt extract_all`)
** [ ] Flag vocabularies that do not exist in anthro
** [ ] Generate ingest CSV of terms that need to be added to vocabularies that do exist in anthro
** [ ] Extract any terms in vocabulary-controlled fields that are not refnames and determine what to do with them

* Authorities
** [x] Extract all authority refnames used, parse, and write to usages file (`thor at usages` => >1GB CSV file)
** [x] Split up/reformat usages file so that it is reasonably usable
*** [x] Unique usages with usage counts (`thor at uniq_usages`)
** [x] Extract any values in authority-controlled fields (`thor at non_refnames`)

=== Reporting/deciding/misc based on extracted data

* [ ] Authority controlled field values that are not refnames

=== Preprocess

All tables get the following transforms applied:

* [ ] Delete empty fields
** 2026-05-06 - Preprocessing is only implemented for main tables at the moment

Per-table category preprocessing:

* Main record types that are authorities
** [x] Extract the preferred term to `ingestid` field. Originally I was going to extract this from the `refname` value, but then I remembered that so many odd things are found in the refnames here, so I https://github.com/dts-hosting/migration-cspace-omca/blob/main/lib/omca/xforms/merge_preferred_term.rb[merged in the preferred term from the relevant termgroup table].
** [x] Identify unused authority terms and tag them `:term_is_used` = `n`

* All main record types
** [x] Disambiguate duplicate `ingestid` values

=== Fix

This layer applies identified fixes to:

* Preprocess output
** [ ] Drop unused authorities

* Any additional extracted artifacts (such as authority usage lists)
** [x] https://3.basecamp.com/3410311/buckets/46717409/todos/9860743606[Fix malformed concept refnames in term usages] - Refname is normal in concepts_common table

=== FCAR

* [ ] Need to collapse used forms of authority refnames to preferred form, retaining/summing usage of all forms of that term. Prepare worksheet to allow OMCA to adjust the preferred form of any terms used more than 9999{empty}footnote:[Asked if we've identified threshold at which updating becomes a problem here: https://lyrasis.slack.com/archives/C08CUAV2ESX/p1778079849399689] times. Use https://3.basecamp.com/3410311/buckets/46717409/todos/9801121304[Oakland and San Francisco] as examples
**  Merge should leave existing refname and shortidentifier the same, but change `ingestid` of relevant authorities.

=== Skeleton

First we load the "rectypes_common" table data for main record types with:

* disambiguated human readable record id
* contents of any other fields from *_common table not populated by authorities or optionlists

This allows us to:

* Have all necessary records in place for populating fields with authorities
* Show some progress
* Implement uri/csid lookups between migrating and migrated data
* Load relationships when we are ready

=== ...and more phases to be fully documented

* merge of non-custom, non-authority values from other tables into main tables/rectypes
* handling/merge of otherwise non-custom freetext, authority, or vocabulary controlled fields that become optionlists in anthro (and any other vocabulary source-only changes)
* merge of non-custom authority controlled fields
* reshaping/remapping custom fields
* Media file ingest

=== Reporting

* [ ] Unused authority terms that will be dropped from migration
