:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= OMCA (Oakland Museum of California) CollectionSpace migration

[IMPORTANT]
.*GitHub repository visibility*
====
Unlike most of our migration repositories, this one is publicly viewable. This is because:

* This migration code is almost entirely based on the patterns of data structures in CollectionSpace, which is open source
* Because it is based on known CollectionSpace data structures, little-to-no actual information about the client data is in the code
* Needing folks outside this GitHub organization to be able to see documentation in this repository, at least while the project is ongoing
====

toc::[]

== Summaries

=== Authority prep/processing

We have to make a distinction between:

* Established authority records/terms, many of which may not be used anywhere
* The usages of terms in record fields

Because of the https://collectionspace.atlassian.net/wiki/spaces/CUD/pages/3566862447/CSV+Importer+Known+Limitations#Repeatable-fields-populated-by-multiple-authorities---order-of-terms-from-different-authorities[multi-authority-controlled field ingest limitation/bug], we will be ingesting REFNAMES instead of authority strings.

The main prep work for authorities is:

* Fix problems with usages (see below)
* Remove usages from fields that are uncontrolled in target instance; remap usages to expected fields in target system where necessary
* Identify non-used terms (which we do not load, except for locations and taxon)
* Load skeleton authority terms in target instance
* Retrieve CSIDs and refnames for terms in target instance
* Prepare lookup between source and target refnames
* Update usages with target refnames
* Merge target refname usages into the tables/fields where they are used

Problems with usages that are addressed:

* `nuke_bom` phase - Removal of BOM from values in all original tables
* non-refname usages extracted, auto-matched or FCAR matched to `nuke_bom`-ed refnames via term match - values in authority controlled fields that are not the expected refname URNs
* `authorities__usages`- Extract all refname URN usages
* `authorities__fix_malformed_usages` - bad concept refnames fixed; citations with no form dropped
* `non_refname_auth__usages_final` - adds fixed non-refname uses to `authorities__fix_malformed_usages`
* `authorities__fix_usages` - delete usages in fields that are uncontrolled in target CollectionSpace
* extract, auto-match or FCAR match unlinked refname usages - refnames that do not match an established term
* BigAuth FCAR - Altering the preferred form of terms with too many usages to update the term in-system

== Migration stages

=== Extract

Pull the tables from the database, in CSV format.

* [x] Soft-deleted record data still in the database is omitted
* [x] Ensures the necessary id values for linkage outside the database are present

[NOTE]
====
Initially I planned to apply https://github.com/lyrasis/collectionspace-sql/blob/main/common_patterns.adoc#converting-date-values-to-site-timezone[the timezone shift required to export accurate date/times from hosted instances].

However, I determined that the database timezone was set to Pacific, not UTC. I confirmed on 2026-04-30 that stored date values in db, as-is, match expected data values in UI/XML.
====

The following commands (and associated https://github.com/dts-hosting/migration-cspace-omca/blob/main/lib/omca/db/queries.rb[queries]) are used extract the data from the database:

----
thor db:addtl_fields
thor db:blobs
thor db:contacts
thor db:extension_field_group
thor db:extension_subgroup
thor db:main
thor db:repeatable_field
thor db:repeatable_field_group
thor db:repeatable_in_group
thor db:structured_dates
thor db:subgroup
----

`thor db:missing_id` is then run to verify all query output includes the expected id values

`thor db:tables_and_columns` can be used to pull a list of all fields in all tables.
I used this to match rows in Jessi's mappings spreadsheet table to the database table in which the data is stored.

The main record types in the source data are:

* collectionobject
* acquisition
* claim
* conditioncheck
* conservation
* exhibition
* group
* loanin
* loanout
* intake
* media
* movement
* objectexit
* restrictedmedia
* valuationcontrol
* citation
* concept
* location
* organization
* person
* place
* taxon

The main_tables extraction for these record types pulls the core, single-valued field data for each record type.

There are 154 other tables containing data that belongs to these record types.
These tables are categorized by the pattern of how the data in them gets merged into the main record types:

addtl_fields:: One row per main table row; Adds single-valued, standalone fields to core; All are custom to OMCA, and will need remapping according to specifications prepared by Jessi/Jadeen/OMCA.
extension_field_group:: The same as `repeatable_field_group`, except the field group is defined and used in multiple main record types.
extension_subgroup:: The same as `subgroup`, except the field subgroup is defined and used in multiple main record types.
repeatable_field:: One or more rows per main table row; Data from standalone multi-valued fields, such as a list of inventory statuses. Position of each value is indicated. Null `item` values removed.
repeatable_field_group:: One or more rows per main table; Data from repeatable groupings of fields, or "field blocks"; Position of each block is indicated.
repeatable_in_group:: One or more rows per group table row; Data from repeatable single field _inside a repeatable field block_; Positionality in play
subgroup:: One or more rows per group_table row; Data from repeatable a repeatable field block inside another repeatable field block; Position of each block is indicated.
subrecord:: Blob and contact tables
structured_dates:: Combined data from `dategroup` and `structureddategroup` tables, in two files based on whether the date is top-level in record, or nested inside a field group; Both of these extracted tables have multiple target record types and different target date fields within those.

Other extract tasks:

* Vocabularies (Term Lists)
** [x] Extract all vocabulary terms used (`thor vt extract_all`)
** [ ] Flag vocabularies that do not exist in anthro
** [ ] Generate ingest CSV of terms that need to be added to vocabularies that do exist in anthro

* Authorities
** [x] Extract all authority refnames used, parse, and write to usages file (`thor run job authorities__usages` => >1GB CSV file)
** [x] Split up/reformat usages file so that it is reasonably usable
*** [x] Unique usages with usage counts (`thor run job authorities__uniq_usages`)
** [x] Extract any non-refname values in authority-controlled fields (`thor run job non_refname_auth__usages`)

* Option Lists
** [x] Extract all values used in source fields that map to target fields controlled by option lists
** [ ] Configure Lyrasis hosted UI config with option list customizations

=== Malformed usage fixes

Required to do other fixes/reporting on authority usages

* [x] https://3.basecamp.com/3410311/buckets/46717409/todos/9860743606[Fix malformed concept refnames in term usages] - Refname is normal in concepts_common table
* [x] https://3.basecamp.com/3410311/buckets/46717409/documents/9846420732#__recording_9861241695[Delete straggler citation usages]

=== Reporting/deciding/misc based on extracted data

* [x] Create report of Authority controlled field values that are not refnames (`thor run job non_refname_auth__refname_lookup`)
* [x] Create report of Unlinked authority usages -- these are well-formed refname usages of authority terms, but when you try to identify the authority record for the term based on the id portion of the refname, there is no record. (`thor run job unlinked_auth__uniq_usages_explode`)

=== Non-refname authority usages

- [x] Programmatically match to existing terms to get refnames to use (`thor run job non_refname_auth__refname_lookup`)
- [x] Create FCAR worksheet for Migration Specialist to provide refnames for ones that did not get programmatically matched, where Migration Specialist could unambibuously identify the correct refname to use and the assignment would not require population of a different field (`thor run job non_refname_auth__worksheet`)
- [x] Merge programmatically and manually provided usages into `authorities\__usages` (`thor run job non_refname_auth__usages_final`)
- [x] Compile uniq usages after merge (`thor run job non_refname_auth__usages_uniq_final`)
- [x] Create report of individual usages where no existing refname was identified programmatically or manually, and ask client to resolve in existing instance. Unresolved non-refname authority usages still in the data at the time of final migration will be dropped. (`thor run job non_refname_auth__not_matched_client_cleanup`, https://3.basecamp.com/3410311/buckets/46717409/todos/10021612471[Basecamp To-Do])

=== Authority usage fixes

`thor run job authorities__fix_usages`

* [x] Remove usages for authority fields migrating to uncontrolled fields (marked `mapping_treatment` = `uncontrol and remove usage` in mappings tab of spreadsheet.

=== Unlinked authority refnames

These are refname URI values used to populate fields, but where no authority record with the `shortidentifier` encoded in the refname can be found in the authority vocabulary encoded in the refname.

* [x] Programmatically match to existing terms in specified authority vocabulary to identify a correct, linked to authority record, refname to use (`thor run job unlinked_auth__refname_lookup`)
* [x] Create FCAR worksheet for Migration Specialist to manually provide correct existing refnames for usages of unlinked auth refnames where the term is used many times
* [x] Merge programmatically and manually corrected refnames into usages (`thor run job unlinked_auth__usage_merge`)
* [x] Create initial report of uncorrected usages for client cleanup pre-migration (`thor run job unlinked_auth__client_cleanup`)
* [ ] FRESH DATA: Create initial report of uncorrected usages for client cleanup post-migration, merging in new record CSIDs and field names as applicable

=== BigAuth FCAR

* [x] Prepare worksheet to allow OMCA to adjust the preferred form of any terms used more than 9999{empty}footnote:[Asked if we've identified threshold at which updating becomes a problem here: https://lyrasis.slack.com/archives/C08CUAV2ESX/p1778079849399689] times. Use https://3.basecamp.com/3410311/buckets/46717409/todos/9801121304[Oakland and San Francisco] as examples

Worksheet processing (in FCAR process)

* [x] Tag collapsing terms (corrected form matches a form that exists as a separate record)

Merge logic - This needs to be done before authorityprep/fixing, which tag used terms and drop unused terms based on the usages file that this updates.

* Collapsing terms (the correction is to a form that exists as a separate record)
** [x] update usages to use corrected refname

=== Preprocess

`thor jobs tagged preprocess -r`

==== all tables

* [x] Delete empty fields
* [x] Replace `|` with \u{2758}
* [x] DeURN vocabulary terms
* [x] Delete timestamps with 00, 16, and 17 hour values from end of fields - Non-structured date values must be imported without timestamps

==== main - non-authority

* [x] Disambiguate duplicate `ingestid` values (**unless authority**)

==== main - authority

* [x] Extract the preferred term to `ingestid` field. Originally I was going to extract this from the `refname` value, but then I remembered that so many odd things are found in the refnames here, so I https://github.com/dts-hosting/migration-cspace-omca/blob/main/lib/omca/xforms/merge_preferred_term.rb[merged in the preferred term from the relevant termgroup table].

==== repeatable_field_group - authority

* [x] Merge :shortidentifier in from parent record

==== structured_dates

* [x] Delete rows where all `Omca::StructuredDate.data_fields` are empty. This takes us from 926990 to 692823 top-level structured dates, and from 133037 to 315 nested structured dates.

=== Authorityprep

==== BigAuth FCAR - Non-collapsing terms merge

* [x] merge into main table should leave existing refname and shortidentifier the same, but change `ingestid` of relevant authorities.
* [x] merge into termtable must account for the corrected form potentially existing as a variant, and setting term group fields appropriately

==== Tag unused terms

* [x] main: Identify unused authority terms and tag them `:term_is_used` = `n`, EXCEPT for location and taxon authorities, where we are migrating unused terms
* [x] repeatable_field_group: Merge in `:term_is_used` value from parent record

==== Duplicate `ingestid` disambiguation

**** [x] check for duplicates on normalized-for-CollectionSpace-authority-shortidentifier values
**** [x] check is within the given authority vocabulary
**** [x] omit unused terms from duplicate check - there are categories of terms we are retaining though they are unused, so make sure we've done that re-tagging (removing the unused tag) prior to doing this duplicate check.

=== Fix

`thor jobs tagged fix -r`

* repeatable_field/collectionobjects_common_responsibledepartments.csv
** [x] Keep only "Art Department", "History Department", and "Science Department"
** [x] Delete " Department" from the end of values

* Uncontrol, keeping label from whatever refname is in the field
** [x] source fields marked `mapping_treatment` = `uncontrol` in mappings tab of spreadsheet
** [x] source fields marked `mapping_treatment` = `uncontrol and remove usage` in mappings tab of spreadsheet

* Option list value tweaks
** [x] downcase and adjust relevant values in fix phase (when values are re-extracted, list should be clean)

=== FCAR merge

`thor jobs tagged fcarmerge -r`

(nothing here yet)

=== Skeleton

First we load the "rectypes_common" table data for main record types with:

* disambiguated human readable record id
* contents of any other fields from *_common table not populated by authorities or optionlists
* any data from addtl_fields table types that does not involve controlled fields or remapping
* any data from repeatable_field table types that does not involve controlled fields or remapping

This allows us to:

* Have all necessary records in place for populating fields with authorities
* Show some progress
* Implement uri/csid lookups between migrating and migrated data
* Load relationships when we are ready

Implement for:

* [x] objects
* [x] procedures
* [x] authorities - needs to split into separate files per authority vocabulary

=== Relations (not really a phase since nothing else depends on it)

* [x] identify existing relationship types - `rel_info__types_uniq`
* [x] apply any recordtype remappings
* [x] insert any migration-generated relations
* [x] map to recordtypes
* [x] split into hier and non-hier: `rel_info__hier_rels` and `rel_info__nonhier_rels`
* [x] develop recordtype -> document type mapping

* authority hierarchy
** need to get authority type vs subtype
** [x] extract source data
** [x] fix / merge in new csids
** [x] prepare load files

* object hierarchy
** include relationshipmetatype in query
** [x] extract source data
** [x] merge in new csids
** [x] prepare load files

* nonhierarchical - based on existing database
** `predicate` and `predicatedisplayname` values are present. We do not have a way to ingest these.
** [x] extract source data
** [x] fix
*** Deduplicate if subject and object are the same
*** Merge in new ids
** [x] Implement check report
*** 1 collectionobject/media relation with unlinked media is expected here and will be dropped during ingest prep
*** 14 unlinked acquisition/valuation relation with unlinked acquisition (deleted records?)
** [x] ingest prep
*** Delete csid fields
*** Delete any rows without subject and object

=== Authority merge

* [x] Once all used authorities are loaded, *prepare old refname to new refname lookups*
* [x] Create new version of usages with new refnames merged in

==== Special handling

* [ ] assocplacegroup.assocplace usages map to collectionobject /controlledcontentplaces/controlledcontentplace

=== ...and more phases to be fully documented

* merge of non-custom, non-authority values from other tables into main tables/rectypes
* handling/merge of otherwise non-custom freetext, authority, or vocabulary controlled fields that become optionlists in anthro (and any other vocabulary source-only changes)
* merge of non-custom authority controlled fields
* reshaping/remapping custom fields
* Media file ingest

=== Reporting

* [ ] Unused authority terms that will be dropped from migration - Done, but need to also implement generating this raw report now that fixes are implemented

=== Media migration

* [x] Produce mappings of new db ids for `media_common` and `restrictedmedia_common` and the old `blobcsid` value to be merged into each

Hopefully that's all and Michael can take care of the rest in the database. 🤞
