:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= OMCA (Oakland Museum of California) CollectionSpace migration

toc::[]

== Migration stages

=== Extract

Pull the tables from the database, in CSV format.

* Soft-deleted record data still in the database is omitted
* +++<s>Applies timezone shift to date/times.</s>+++ - Database timezone set to Pacific, not UTC; Confirmed on 2026-04-30 that stored date values in db match expected data values in UI/XML.
* Ensures the necessary id values for linkage outside the database are present

The following commands are used to make this happen:

----
thor db:addtl_fields_tables     # Write other direct-id-linked tables to `addtl_fields` dir as CSV
thor db:blobs                   # Write main blobs table to `subrecord` dir as CSV
thor db:contacts                # Write main contacts table to `subrecord` dir as CSV
thor db:group_tables            # Write repeatable field group tables to `field_groups` dir as CSV
thor db:main_tables             # Write main tables to `main_rectype` dir as CSV
thor db:repeating_field_tables  # Write repeating field tables to `repeating` dir as CSV
thor db:subgroup_tables         # Write repeatable field subgroup tables to `field_subgroups` dir as CSV
----

The main record types in the source data are:

* collectionobject
* acquisition
* claim
* conditioncheck
* conservation
* exhibition
* group
* loanin
* loanout
* intake
* media
* movement
* objectexit
* restrictedmedia
* valuationcontrol
* citation
* concept
* location
* organization
* person
* place
* taxon

The main_tables extraction for these record types pulls the core, single-valued field data for each record type.

There are 154 other tables containing data that belongs to these record types.
These tables are categorized by the pattern of how the data in them gets merged into the main record types:

addtl_fields_tables:: One row per main table row; Adds single-valued, standalone fields to core; *All are custom to OMCA, and will need remapping according to specifications prepared by Jessi/Jadeen/OMCA.
repeating_field_tables:: One or more rows per main table row; Data from standalone multi-valued fields, such as a list of inventory statuses. Position of each value is indicated. Null `item` values removed.
group_tables:: One or more rows per main table; Data from repeatable groupings of fields, or "field blocks"; Position of each block is indicated.
repeatable_in_group_tables:: One or more rows per group table row; Data from repeatable single field _inside a repeatable field block_; Positionality in play
subgroup_tables:: One or more rows per group_table row; Data from repeatable a repeatable field block inside another repeatable field block; Position of each block is indicated.
structured_dates:: Combined data from `dategroup` and `structureddategroup` tables, in two files based on whether the date is top-level in record, or nested inside a field group; Both of these extracted tables have multiple target record types and different target date fields within those.

=== Preprocess

All tables get the following transforms applied:

* Delete empty fields

Per-table category preprocessing:

* Main record types that are authorities
** Extract the preferred term from `refname` value to `ingestid` field
* All main record types
** Disambiguate duplicate `ingestid` values
